App\Entity\Product:
  attributes:
    id:
      groups: ['product_read']
    title:
      groups: ['product_read']
    description:
      groups: ['product_read']
    identifier:
      groups: ['product_read']
